### ISSUE TITLE
Column types should be generic

### ISSUE THREAD

**Issue by dtourek** [flsy/ui#72]
DataTable component has columns prop which is typed as: `columns?: IColumns;` and 
```
export type AllTypes = 'string' | 'number' | 'boolean' | 'timestamp' | 'image';
type IColumns = Columns<AllTypes>
```

When we have our own columns which differs from AllTypes: 
```
const columns: Columns<T> = {
params: {
    type: 'params',
    label: 'Params'
  }
}
```

it would be good if we can pass generic type to columns: `const [columns, setColumns] = useState<Columns<T>>(columns)`

**Comment by smidhonza** [comment]
opraveno
